spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: findstore!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update